language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
addons:
  code_climate:
    repo_token: a1558e08cc885c164046e284ef205aadb193105c6a7e221ba15b732a33b370b2
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt test
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
